[package]
name = "csgo-gsi-payload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.149", features = ["derive"] }
serde_json = { version = "1.0.89" }
serde_with = "2.1.0"
